version: '3'

services:
  php-fpm:
    build:
      context: .docker/php-fpm
    volumes:
      - ./src:/var/www
    networks:
      - database
      - server

  nginx:
    build:
      context: .docker/nginx
    volumes:
      - ./src:/var/www
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/sites/:/etc/nginx/sites-available
      - .docker/nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - server
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  database:
    build:
      context: .docker/database
    environment:
      - MYSQL_DATABASE=project_database
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      -  db-data:/var/lib/mysql
      - .docker/database/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    networks:
      - database
    links:
      - database
    environment:
      PMA_HOST: database

volumes:
    db-data:
networks:
  database:
  server: